<?php
/**
 * Created by PhpStorm.
 * User: liuyong
 * Date: 5/7/16
 * Time: 7:51 PM
 */

namespace People;

require_once 'People.php';

class Man extends \People
{
    //重写构造方法
    public function __construct($age, $name)
    {
        parent::__construct($age, $name,"男");
    }

    public function hi()
    {
        parent::hi(); // TODO: Change the autogenerated stub
        echo "重写父类的防范";
    }
}
